version: '3.9'

services:
  mysql:
    image: mysql:8.1
    container_name: attendance-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: attendanceDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: attendance-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: attendanceDB
      DB_DIALECT: mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
