apiVersion: v1
kind: ConfigMap
metadata:
  name: attendance-config
  namespace: attendance
data:
  db.host: "mysql.attendance.svc.cluster.local"
  db.port: "3306"
  db.name: "attendanceDB"
  app.env: "production"
