apiVersion: v1
kind: Service
metadata:
  name: attendance-app
  namespace: attendance
  labels:
    app: attendance-event
spec:
  type: LoadBalancer
  selector:
    app: attendance-event
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP
  sessionAffinity: None
